// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvywozmfdwcstmhwrdad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2eXdvem1mZHdjc3RtaHdyZGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDQ4MjksImV4cCI6MjA2MDIyMDgyOX0.IB_tW2jx23KD-OgFV6ns35mVfemwxRfjC9E-F50Q-Z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});